### ISSUE TITLE
This looks really cool! How can I get in touch with you?

### ISSUE THREAD

**Issue by kevmodrome** [timothycohen/samplekit#5]
Hey Timothy! Looked around and couldn't find a way to reach out to you so just creating this issue so you'll see it. 😬 

I'd love to chat with you and (if you're down for it) have you on Svelte Radio as a guest! Can you reach out to me on X (@kevmodrome) or email (kevin `@` sveltesociety.dev)?

**Comment by timothycohen** [comment]
Thanks for reaching out Kevin! I'm available at [contact@timcohen.dev](mailto:contact@timcohen.dev), and I'll follow up from there.

PS – I very much appreciate everything Svelte Society has done for the ecosystem!
